version: '3.6'

services:
  app:
    build: .

    env_file: ./config/docker.env

    volumes:
      - .:/workspace:delegated
      - node_modules:/workspace/node_modules

  mosquitto:
    image: eclipse-mosquitto

    expose:
      - '1883'
      - '9001'

volumes:
  node_modules:

